### ISSUE TITLE
Use jest.genMockFn() and other jest stuff for mocks to be more facebook way 

### ISSUE THREAD

**Issue by vitalets** [lelandrichardson/react-native-mock#2]

**Comment by lelandrichardson** [comment]
@vitalets I'm trying to make this library not have a dependency on jest.

**Comment by vitalets** [comment]
ok. But could you describe recommended way to calc calls of some method?

**Comment by lelandrichardson** [comment]
@vitalets I'm not that familiar with jest, but I assume you can still use it just fine.

If you were using sinon, you could do something like the following:

``` js
import sinon from 'sinon';
import React, { NativeModules } from 'react-native';

it('gets called', () => {
  sinon.spy(NativeModules.ScrollViewManager, 'scrollTo');
  // do something that scrolls
  assert(NativeModules.ScrollViewManager.scrollTo.calledOnce, 'got scrolled');
});
```

I assume jest has some of the same capabilities?

**Comment by vitalets** [comment]
Yes, similar way. 
I mean is not it can be useful to automatically wrap react native mocked method into spies? (sinon, jest or whatever)
In that case we reduce boilerplate code, and your example will be:

``` js
it('gets called', () => {
  // do something that scrolls
  assert(NativeModules.ScrollViewManager.scrollTo.calledOnce, 'got scrolled');
});
```

**Comment by lelandrichardson** [comment]
I agree it would reduce some boilerplate, but I'm not sure it's something I want this library to be opinionated about. If people want to use sinon or jest or {some other library}, then that is their choice.

For these things to be useful, it is often good to have a sort of "setup" and "teardown" feature so that information doesn't leak across tests. This involves making assumptions about one's test environment, which are not usually safe to make.

There are ways for the user to reduce the boilerplate themselves by making helper methods to iterate over an object in the exported API.

**Comment by vitalets** [comment]
Okey, thanks!
